<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Content.Integration.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <NoWarn>$(NoWarn);xUnit1051;EF1001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />

        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="AwesomeAssertions.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Testcontainers.Redis" />
        <PackageReference Include="Respawn" />
        <PackageReference Include="Bogus" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="EFCore.NamingConventions" />

        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../Identity/Identity/tests/Identity.TestData/Identity.TestData.csproj" />
        <ProjectReference Include="../../../../Storage/Storage/tests/Storage.TestData/Storage.TestData.csproj" />
        <ProjectReference Include="../../src/Content.Domain/Content.Domain.csproj" />
        <ProjectReference Include="../../src/Content.Application/Content.Application.csproj" />
        <ProjectReference Include="../../src/Content.Infrastructure/Content.Infrastructure.csproj" />
        <ProjectReference Include="../Content.TestData/Content.TestData.csproj" />
        <ProjectReference Include="../../../../../../tests/Fixtures/Fixtures.csproj" />
        <ProjectReference Include="../../../../../../tests/TestData/TestData.csproj" />
    </ItemGroup>
</Project>
