<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Storage.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../shared/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Storage.Application" />
        <InternalsVisibleTo Include="Storage.Unit.Tests" />
        <InternalsVisibleTo Include="Storage.TestData" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
