<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Content.TestData</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" />
        <PackageReference Include="Moq" />
        <PackageReference Include="SixLabors.ImageSharp" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Content.Domain/Content.Domain.csproj" />
        <ProjectReference Include="../../src/Content.Application/Content.Application.csproj" />
        <ProjectReference Include="../../src/Content.Infrastructure/Content.Infrastructure.csproj" />
        <ProjectReference Include="../../../../../../tests/TestData/TestData.csproj" />
    </ItemGroup>
</Project>
