<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Identity.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Identity.Application" />
        <InternalsVisibleTo Include="Identity.Infrastructure" />
        <InternalsVisibleTo Include="Identity.Unit.Tests" />
        <InternalsVisibleTo Include="Identity.Integration.Tests" />
        <InternalsVisibleTo Include="Identity.TestData" />
        <InternalsVisibleTo Include="Fixtures" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../../shared/src/Shared.Domain/Shared.Domain.csproj" />
        <ProjectReference Include="../../../../../shared/src/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj" />
    </ItemGroup>
</Project>
