<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Content.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Content.Application" />
        <InternalsVisibleTo Include="Content.Infrastructure" />
        <InternalsVisibleTo Include="Content.Unit.Tests" />
        <InternalsVisibleTo Include="Content.Integration.Tests" />
        <InternalsVisibleTo Include="Content.TestData" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../../shared/src/Shared.Domain/Shared.Domain.csproj" />
        <ProjectReference Include="../../../../../shared/src/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj" />
    </ItemGroup>
</Project>
