<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Mailer.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Mailer.Unit.Tests" />
        <InternalsVisibleTo Include="Mailer.Integration.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Mailer.Application/Mailer.Application.csproj" />
    </ItemGroup>
</Project>
