global using System.Net;
global using System.Net.Http.Json;
global using _116.Tests.Fixtures;
global using _116.Tests.Fixtures.Base;
global using _116.Tests.Fixtures.Extensions;
global using static _116.Tests.TestData.Constants.TestConstants;
global using AwesomeAssertions;
global using Microsoft.EntityFrameworkCore;
global using Xunit;
global using TestUser = _116.Tests.TestData.Constants.TestConstants.User;
