<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <RootNamespace>_116.Identity</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.csproj" />
        <ProjectReference Include="../../../Shared/Shared/Shared.csproj" />
        <ProjectReference Include="../../../Shared/Shared.Contracts/Shared.Contracts.csproj" />
        <ProjectReference Include="../../Core/Core/Core.csproj" />
        <ProjectReference Include="../Identity.Contracts/Identity.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="CsvHelper" Version="33.1.0" />
        <PackageReference
            Include="Microsoft.AspNetCore.Authentication.JwtBearer"
            Version="8.0.11"
        />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.1" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
        <PackageReference Include="Wangkanai.Detection" Version="8.20.0" />
    </ItemGroup>
</Project>
