<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../Shared/Shared/Shared.csproj" />
        <ProjectReference Include="../../../Shared/Shared.Contracts/Shared.Contracts.csproj" />
        <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.csproj" />
        <ProjectReference Include="../Core.Contracts/Core.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CloudinaryDotNet" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Polly.Core" />
        <PackageReference Include="SixLabors.ImageSharp" />
    </ItemGroup>
</Project>
