<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <NoWarn>$(NoWarn);xUnit1051;EF1001</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <RootNamespace>_116.Integration.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Testcontainers.Redis" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="AwesomeAssertions.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Bogus" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="Respawn" />
        <PackageReference Include="EFCore.NamingConventions" />

        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Api\Api.csproj" />
        <ProjectReference Include="..\..\src\Modules\Identity\Identity\Identity.csproj" />
        <ProjectReference Include="..\..\src\Modules\Content\Content\Content.csproj" />
        <ProjectReference Include="..\..\src\Modules\Mailer\Mailer\Mailer.csproj" />
        <ProjectReference Include="..\..\src\Modules\Core\Core\Core.csproj" />
        <ProjectReference Include="..\..\src\Shared\Shared\Shared.csproj" />
        <ProjectReference Include="..\..\src\Shared\Shared.Contracts\Shared.Contracts.csproj" />
        <ProjectReference Include="..\..\src\BuildingBlocks\BuildingBlocks.csproj" />
        <ProjectReference Include="..\Fixtures\_116.Tests.Fixtures.csproj" />
    </ItemGroup>
</Project>
