<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Mailer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="_116.Unit.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../BuildingBlocks/BuildingBlocks.csproj" />
        <ProjectReference Include="../../../Shared/Shared/Shared.csproj" />
        <ProjectReference Include="../../../Shared/Shared.Contracts/Shared.Contracts.csproj" />
        <ProjectReference Include="../Mailer.Contracts/Mailer.Contracts.csproj" />
        <ProjectReference Include="../../Identity/Identity.Contracts/Identity.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Infrastructure\Persistence\Migrations\" />
    </ItemGroup>
</Project>
