<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Storage.Unit.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />

        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="AwesomeAssertions.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Moq" />
        <PackageReference Include="Bogus" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="EFCore.NamingConventions" />

        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Storage.Domain/Storage.Domain.csproj" />
        <ProjectReference Include="../../src/Storage.Application/Storage.Application.csproj" />
        <ProjectReference Include="../../src/Storage.Infrastructure/Storage.Infrastructure.csproj" />
        <ProjectReference Include="../Storage.TestData/Storage.TestData.csproj" />
        <ProjectReference Include="../../../../../../tests/TestData/TestData.csproj" />
    </ItemGroup>
</Project>
