<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.EndToEnd.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <NoWarn>$(NoWarn);xUnit1051;EF1001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />

        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="AwesomeAssertions.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Testcontainers.Redis" />
        <PackageReference Include="Respawn" />
        <PackageReference Include="Bogus" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="EFCore.NamingConventions" />

        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/modules/Content/Content/src/Content.Domain/Content.Domain.csproj" />
        <ProjectReference Include="../../src/modules/Content/Content/src/Content.Application/Content.Application.csproj" />
        <ProjectReference Include="../../src/modules/Content/Content/src/Content.Infrastructure/Content.Infrastructure.csproj" />
        <ProjectReference Include="../../src/modules/Identity/Identity/src/Identity.Domain/Identity.Domain.csproj" />
        <ProjectReference Include="../../src/modules/Identity/Identity/src/Identity.Application/Identity.Application.csproj" />
        <ProjectReference Include="../../src/modules/Identity/Identity/src/Identity.Infrastructure/Identity.Infrastructure.csproj" />
        <ProjectReference Include="../../src/modules/Storage/Storage/src/Storage.Domain/Storage.Domain.csproj" />
        <ProjectReference Include="../../src/modules/Storage/Storage/src/Storage.Application/Storage.Application.csproj" />
        <ProjectReference Include="../../src/modules/Storage/Storage/src/Storage.Infrastructure/Storage.Infrastructure.csproj" />
        <ProjectReference Include="../../src/modules/Mailer/Mailer/src/Mailer.Domain/Mailer.Domain.csproj" />
        <ProjectReference Include="../../src/modules/Mailer/Mailer/src/Mailer.Application/Mailer.Application.csproj" />
        <ProjectReference Include="../../src/modules/Mailer/Mailer/src/Mailer.Infrastructure/Mailer.Infrastructure.csproj" />
        <ProjectReference Include="../../src/modules/Content/Content/tests/Content.TestData/Content.TestData.csproj" />
        <ProjectReference Include="../../src/modules/Identity/Identity/tests/Identity.TestData/Identity.TestData.csproj" />
        <ProjectReference Include="../../src/modules/Storage/Storage/tests/Storage.TestData/Storage.TestData.csproj" />
        <ProjectReference Include="../../src/modules/Mailer/Mailer/tests/Mailer.TestData/Mailer.TestData.csproj" />
        <ProjectReference Include="../Fixtures/Fixtures.csproj" />
        <ProjectReference Include="../TestData/TestData.csproj" />
    </ItemGroup>
</Project>
