<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" />
        <PackageReference Include="Bogus" />
        <PackageReference Include="Carter" />
        <PackageReference Include="DotNetEnv" />
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.AspNetCore" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Mapster" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Quartz.AspNetCore" />
        <PackageReference Include="Quartz.Serialization.SystemTextJson" />
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="_116.Integration.Tests" />
        <InternalsVisibleTo Include="_116.Unit.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Shared.Contracts/Shared.Contracts.csproj" />
        <ProjectReference Include="../../BuildingBlocks/BuildingBlocks.csproj" />
    </ItemGroup>
</Project>
