<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <RootNamespace>_116.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Modules/Core/Core/Core.csproj" />
        <ProjectReference Include="../Modules/Identity/Identity/Identity.csproj" />
        <ProjectReference Include="../Modules/Content/Content/Content.csproj" />
        <ProjectReference Include="../Modules/Mailer/Mailer/Mailer.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
        <PackageReference Include="AspNetCore.HealthChecks.Redis" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Seq" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>
</Project>
