<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Storage.TestData</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" />
        <PackageReference Include="Moq" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Storage.Domain/Storage.Domain.csproj" />
        <ProjectReference Include="../../src/Storage.Application/Storage.Application.csproj" />
        <ProjectReference Include="../../src/Storage.Infrastructure/Storage.Infrastructure.csproj" />
        <ProjectReference Include="../../../../../../tests/TestData/TestData.csproj" />
    </ItemGroup>
</Project>
