<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <RootNamespace>_116.Tests.Fixtures</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus" Version="35.6.3" />
        <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Modules\Identity\Identity\Identity.csproj" />
        <ProjectReference Include="..\..\src\Modules\Core\Core\Core.csproj" />
        <ProjectReference Include="..\..\src\Shared\Shared\Shared.csproj" />
        <ProjectReference Include="..\..\src\Shared\Shared.Contracts\Shared.Contracts.csproj" />
        <ProjectReference Include="..\..\src\BuildingBlocks\BuildingBlocks.csproj" />
    </ItemGroup>
</Project>
