<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>_116.Shared.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Shared.Unit.Tests" />
        <InternalsVisibleTo Include="Shared.Integration.Tests" />
    </ItemGroup>
</Project>
