namespace _116.Content.Domain.Enums;

/// <summary>
/// Represents where a lyrics translation's current text came from.
/// </summary>
public enum EnumTranslationSource
{
    /// <summary>
    /// The text was generated by the AI translation service and has not yet been superseded
    /// by an accepted community revision.
    /// </summary>
    Ai,

    /// <summary>
    /// The text was replaced by an accepted community revision, either via the vote threshold
    /// or a moderator override.
    /// </summary>
    Community,
}
